export {default as ClientDetails} from './ClientDetails'
export {default as PersonalInfo} from './PersonalInfo'
export {default as Statistics} from './Statistics'
export {default as BuyMessages} from './BuyMessages'
export {default as AccountDetails} from './AccountDetails'
export {default as Authorization} from './Authorization'
